apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - nodePort: {{ .Values.api.service.nodePort }}
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.targetPort }}
      name: validator-api
  selector:
    {{- include "api.labels" . | nindent 4 }}
