apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: squad
subjects:
- kind: ServiceAccount
  name: squad
  namespace: squad
roleRef:
  kind: ClusterRole
  name: squad
  apiGroup: rbac.authorization.k8s.io
