apiVersion: v1
kind: Service
metadata:
  name: opensearch
  labels:
    app: opensearch
spec:
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: cluster
  selector:
    app: opensearch
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ index .Values.opensearch.nodes 0 }}-os-0"
  labels:
    app: "{{ index .Values.opensearch.nodes 0 }}-os-0"
spec:
  ports:
    - port: 9200
      name: rest
    - port: 9300
      name: cluster
  selector:
    ssapp: "{{ index .Values.opensearch.nodes 0 }}-os"
