apiVersion: apps/v1
kind: Deployment
metadata:
  name: x-searcher
  labels:
    {{- include "xSearcher.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "xSearcher.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "xSearcher.labels" . | nindent 8 }}
    spec:
      {{- with .Values.xSearcher.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.xSearcher.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.xSearcher.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: jwt-cert
          secret:
            secretName: jwt-cert
            items:
              - key: squad_pub.pem
                path: squad_pub.pem
              - key: squad_priv.pem
                path: squad_priv.pem
      containers:
        - name: searcher
          image: "{{ .Values.xSearcher.image }}"
          imagePullPolicy: {{ .Values.xSearcher.imagePullPolicy }}
          command: ["poetry", "run", "python", "squad/x/searcher.py"]
          env:
            {{- include "squad.sensitiveEnv" . | nindent 12 }}
            {{- include "squad.commonEnv" . | nindent 12 }}
          volumeMounts:
            - name: jwt-cert
              mountPath: "/etc/jwt-cert"
              readOnly: true
          resources:
            {{- toYaml .Values.xSearcher.resources | nindent 12 }}
