apiVersion: v2
name: squad-api
description: Helm chart for chutes.ai powered agent platform Squad
version: 0.0.1
appVersion: "0.0.1"
type: application
maintainers:
  - name: Jon Durbin
    email: jon@chutes.ai
  - name: namoray
    email: namoray@chutes.ai
kubeVersion: ">=1.19.0-0"
